name: Node.js and Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install JavaScript dependencies
      run: |
        npm install

    - name: Run lint
      run: |
        npm run lint
        # Add Python linting command if needed

    - name: Run tests
      run: |
        npm test
        pytest
        
